name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install GCC 14
      run: |
        sudo apt-get update
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
        sudo apt-get install -y gcc-14
    - name: Install libfmt and libgit2
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libfmt-dev  libgit2-dev
    - name: Compile gitalias-libgit
      run: make
